# See GitHub's documentation for more information on this file:
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      # Check for updates to Go modules every weekday
      interval: "daily"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      # Group all terraform-plugin-(go|sdk|framework|testing) dependencies together
      "terraform-plugin":
        patterns:
          - "github.com/hashicorp/terraform-plugin-*"
    open-pull-requests-limit: 10
    reviewers:
      - "@jamesainslie"
    assignees:
      - "@jamesainslie"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"

  # Maintain dependencies for tools directory
  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "@jamesainslie"
    assignees:
      - "@jamesainslie"
    commit-message:
      prefix: "deps(tools)"
      include: "scope"

  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Etc/UTC"
    groups:
      "github-actions":
        patterns:
          - "*" # Group all GitHub Actions dependencies together
    open-pull-requests-limit: 5
    reviewers:
      - "@jamesainslie"
    assignees:
      - "@jamesainslie"
    commit-message:
      prefix: "ci"
      include: "scope"
