# golangci-lint configuration for Terraform Package Provider
# Compatible with golangci-lint v1.61.0 and v2.4.0

version: 2

run:
  timeout: 10m
  tests: true

linters:
  disable-all: true
  enable:
    # Core linters
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    
    # Code quality
    - gocritic
    - revive
    - gocyclo
    - gocognit
    - funlen
    - cyclop
    
    # Style and formatting
    - godot
    - misspell
    - whitespace
    
    # Security
    - gosec
    - bodyclose
    
    # Performance
    - prealloc
    
    # Best practices
    - contextcheck
    - errorlint
    - nilerr
    - wrapcheck
    - goconst
    - lll
    - nolintlint
    - varnamelen

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: if-return
      - name: var-naming
      - name: package-comments

  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  funlen:
    lines: 120
    statements: 60

  cyclop:
    max-complexity: 15

  godot:
    capital: true

  lll:
    line-length: 120

  gosec:
    excludes:
      - G204  # Subprocess launched with variable - needed for package managers

  goconst:
    min-len: 2
    min-occurrences: 3

  varnamelen:
    min-name-length: 2
    ignore-names:
      - err
      - id
      - ok
      - i
      - j
      - k
      - v

  nolintlint:
    require-explanation: true
    require-specific: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - wrapcheck
        - varnamelen
        
    - path: examples/
      linters:
        - errcheck
        - gosec
        - wrapcheck