run:
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gofmt
    - goimports
    - misspell
    - gosec

linters-settings:
    errcheck:
      check-type-assertions: true
    check-blank: false
  gosec:
    excludes:
      - G204
      - G301
      - G302
      - G304

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: examples/
      linters:
        - errcheck
        - gosec
    - text: "Error return value.*is not checked"
      path: _test\.go
  max-issues-per-linter: 0
  max-same-issues: 0