# Changelog generation workflow
name: Changelog

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  # Update changelog on version tags
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate changelog
        uses: orhun/git-cliff-action@v4
        with:
          config: .cliff.toml
          args: --verbose --unreleased --tag 0.1.0
        env:
          OUTPUT: CHANGELOG.md
          
      - name: Commit changelog
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if ! git diff --quiet CHANGELOG.md; then
            git add CHANGELOG.md
            git commit -m "docs: update CHANGELOG.md"
            git push
          fi

  # Create release notes on new releases
  release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - name: Generate release notes
        uses: orhun/git-cliff-action@v4
        with:
          config: .cliff.toml
          args: --verbose --latest --strip header
        env:
          OUTPUT: release-notes.md
          
      - name: Update release description
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-notes.md
          append_body: true
